# What is NumPy?

NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

NumPy stands for Numerical Python.


# Why Use NumPy?

In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

Arrays are very frequently used in data science, where speed and resources are very important.


# Why is NumPy Faster Than Lists?

NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

This behavior is called locality of reference in computer science.

This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

In [1]:
import numpy as np

# Array creation

There are 6 general mechanisms for creating arrays:

    1. From Python lists or tuples
    2. Using NumPy built-in functions
    3. By copying, joining, or reshaping existing arrays
    4. By reading from files (disk)
    5. From raw data (bytes or strings)
    6. Using special library functions (like random)

### 1. From Python lists or tuples

In [2]:
# From a Python list
arr1 = np.array([1, 2, 3, 4])
print(arr1)  



[1 2 3 4]


In [3]:
# From a Python tuple
arr2 = np.array((5, 6, 7))
print(arr2)  

[5 6 7]


In [4]:
type(arr1)

numpy.ndarray

In [5]:
arr1.ndim

1

In [6]:
arr3=np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [7]:
type(arr3)

numpy.ndarray

In [8]:
arr3.ndim

2

### 2. Using NumPy built-in functions

In [9]:
arr4=np.zeros((2,3))
arr4

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
arr5=np.ones((3,3))
arr5

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
arr6=np.identity(5)
arr6

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
arr7=np.arange(10)
arr7

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr7=np.arange(5,10)
arr7

array([5, 6, 7, 8, 9])

In [14]:
arr7=np.arange(1,20,2)
arr7

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [15]:
arr8=np.linspace(10,20,3)
arr8

array([10., 15., 20.])

### 3. By copying, joining, or reshaping existing arrays

In [16]:
arr9 = np.array([1,2,3,4])
arr10 = np.array([5,6,7])

In [17]:
arr11=arr9.copy()
arr11

array([1, 2, 3, 4])

In [18]:
arr12=np.concatenate((arr9,arr10))
arr12

array([1, 2, 3, 4, 5, 6, 7])

In [19]:
arr13 = arr9.reshape(2,2)
arr13

array([[1, 2],
       [3, 4]])

### 4. By reading from files (disk)  

In [20]:
# Save an array to a file
np.savetxt("mydata.txt", np.array([1,2,3,4]))

In [21]:
# Load it back
arr14 = np.loadtxt("mydata.txt")
print(arr14)   # [1. 2. 3. 4.]


[1. 2. 3. 4.]


### 5. From raw data (bytes or strings)   

In [22]:
# From bytes
data = b'\x01\x02\x03\x04'
arr15 = np.frombuffer(data, dtype=np.uint8)
print(arr15)

[1 2 3 4]


In [62]:
# From string
arr16 = np.fromstring("1 2 3 44", sep=" ")
print(arr16) 

[ 1.  2.  3. 44.]


### 6. Using special library functions (like random)

In [24]:
arr17=np.random.rand(5)  # random floats in [0,1)
arr17

array([0.0438624 , 0.13295067, 0.1101096 , 0.38110986, 0.4890203 ])

In [25]:
arr19=np.random.rand(2,3)  # random floats in [0,1)
arr19

array([[0.14103193, 0.54976536, 0.75315913],
       [0.42668311, 0.19266179, 0.81797   ]])

In [63]:
arr20=np.random.randint(100,500,5) # 5 random integers between 1 and 9
arr20

array([234, 120, 428, 266, 373])

# NumPy Array Properties & Attributes

* ndim → Number of dimensions
* shape → Dimensions (rows × columns)
* size → Total number of elements
* dtype → Data type of elementsitem
* itemsize → Memory (bytes) per element
* nbytes → Total memory used
* T → Transpose (rows ↔ columns)
* flags → Memory info (C/F order, writeable, etc.)
* data → Buffer with actual data
* real → Extracts the real part
* imag → Extracts the imaginary part

Copy & Type Conversion (Methods)
* astype() → Convert to another dtype
* copy() → Deep copy of array
* view() → Shallow copy / view

### Basic Info

In [27]:
x = np.array([1,2,3,4,5])
y = np.array([[1,2,3],[4,5,6]])
z = np.array([1+2j, 3+4j, 5+6j]) 
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

In [28]:
print("Shape:", x.shape)    
print("Size:", x.size)      
print("ndim:", x.ndim)      
print("dtype:", x.dtype)    

Shape: (5,)
Size: 5
ndim: 1
dtype: int64


In [29]:
print("Shape:", y.shape)    
print("Size:", y.size)       
print("ndim:", y.ndim)      
print("dtype:", y.dtype)    

Shape: (2, 3)
Size: 6
ndim: 2
dtype: int64


In [30]:
print("Shape:", z.shape)     
print("Size:", z.size)       
print("ndim:", z.ndim)      
print("dtype:", z.dtype)
print("Real number:", z.real) 
print("Imagize number", z.imag) 

Shape: (3,)
Size: 3
ndim: 1
dtype: complex128
Real number: [1. 3. 5.]
Imagize number [2. 4. 6.]


In [31]:
print("Itemsize:", x.itemsize) 
print("Transposed array:", x.data) 
print("nbytes:", x.nbytes)   # memory usage
print("Transposed array:\n", a.T) 
print(" Memory info:\n", x.flags) 


Itemsize: 8
Transposed array: <memory at 0x7bc577cc3100>
nbytes: 40
Transposed array:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
 Memory info:
   C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



### Copy & Type Conversion (Methods) 

In [32]:
y.astype('float')

array([[1., 2., 3.],
       [4., 5., 6.]])

In [33]:
# copy()
copy_x = x.copy()
copy_x[0] = 100
print(x)              # [1 2 3 4 5]  (original unchanged)
print(copy_x)         # [100 2 3 4 5]



[1 2 3 4 5]
[100   2   3   4   5]


In [34]:
# view()
view_x = x.view()
view_x[0] = 200
print(x)              # [200 2 3 4 5]  (original changed, since it's a view)

[200   2   3   4   5]


# Indexing & Slicing

1. Basic Indexing (Single Element)
2. Boolean Indexing
3. Fancy Indexing
4. Slicing (Range of Elements)
5. Step Slicing
      

In [65]:
x = np.array([10, 20, 30, 40, 50])
y = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

###  Basic Indexing (Single Element) 

In [36]:
print(x[0])   # 10 (1st element)
print(x[-1])  # 50 (last element)

print(y[0, 0])  # 1 (row 0, col 0)
print(y[2, 1])  # 8 (row 2, col 1)

10
50
1
8


###  Boolean Indexing

In [37]:
print(x[x > 25])   # [30 40 50] → values greater than 25
print(y[y % 2 == 0])  # [2 4 6 8] → even numbers only


[30 40 50]
[2 4 6 8]


###  Fancy Indexing

In [38]:
print(x[[0, 2, 4]])   # [10 30 50] → pick specific indices
print(y[[0, 2], [1, 2]])  # [2 9] → picks (0,1) and (2,2)


[10 30 50]
[2 9]


###  Slicing (Range of Elements)

In [71]:
print(x[1:4])    # [20 30 40]   → from index 1 to 3
print(x[2:])     # [30 40 50]   → from index 2 to end
print(x[:-1])     # [10 20 30]   → first 3 elements
print(x[-1])

print(y[0:2, 1:3])   # [[2 3]
                     #  [5 6]]


[20 30 40]
[30 40 50]
[10 20 30 40]
50
[[2 3]
 [5 6]]


###  Step Slicing

In [73]:
print(x[::-1])
print(x[::2])   # [10 30 50]  → every 2nd element
print(x[::-1])  # [50 40 30 20 10] → reverse


[50 40 30 20 10]
[10 30 50]
[50 40 30 20 10]


# Array Operations

1. Element-wise Arithmetic
2. Universal Functions (ufuncs)
3. Comparison & Logical Operations

In [41]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])
y = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
z = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

###  Element-wise Arithmetic

In [42]:
print(a + b)   # [11 22 33 44 55]
print(b - a)   # [ 9 18 27 36 45]
print(a * b)   # [ 10  40  90 160 250]
print(b / a)   # [10. 10. 10. 10. 10.]
print(a ** 2)  # [ 1  4  9 16 25]

[11 22 33 44 55]
[ 9 18 27 36 45]
[ 10  40  90 160 250]
[10. 10. 10. 10. 10.]
[ 1  4  9 16 25]


###  Universal Functions (ufuncs)

In [43]:
print(np.sqrt(a))   # [1.         1.41421356 1.73205081 2. 2.23606798]
print(np.exp(a))    # [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
print(np.log(a))    # [0. 0.69314718 1.09861229 1.38629436 1.60943791]
print(np.sin(a))    # [0.84 0.91 0.14 -0.76 -0.99]

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


###  Comparison & Logical Operations

In [44]:
print(a > 2)       # [False False  True  True  True]
print(b <= 30)     # [ True  True  True False False]
print(np.logical_and(a > 2, b < 40))  # [False False  True  True False]

[False False  True  True  True]
[ True  True  True False False]
[False False  True False False]


# Useful Functions

1. Basic Aggregation Functions
2. Axis-wise Operations
3. Cumulative Functions
4. Other Useful Functions

In [45]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

###  Basic Aggregation Functions

In [46]:
print(np.sum(x))       # 15
print(np.min(x))       # 1
print(np.max(x))       # 5
print(np.mean(x))      # 3.0
print(np.std(x))       # 1.4142135623730951
print(np.var(x))       # 2.0

15
1
5
3.0
1.4142135623730951
2.0


###  Axis-wise Operations

In [47]:
# Sum along columns (axis=0)
print(np.sum(y, axis=0))  # [12 15 18]

# Sum along rows (axis=1)
print(np.sum(y, axis=1))  # [ 6 15 24]

# Min & Max along rows/columns
print(np.min(y, axis=0))  # [1 2 3]
print(np.max(y, axis=1))  # [3 6 9]

[12 15 18]
[ 6 15 24]
[1 2 3]
[3 6 9]


###  Cumulative Functions

In [48]:
print(np.cumsum(x))   # [ 1  3  6 10 15] → cumulative sum
print(np.cumprod(x))  # [  1   2   6  24 120] → cumulative product

[ 1  3  6 10 15]
[  1   2   6  24 120]


### Other useful function 

In [49]:
print(np.prod(x))      # Product of all elements → 120
print(np.argmin(x))    # Index of min → 0
print(np.argmax(x))    # Index of max → 4
print(np.median(x))    # Median → 3.0
print(np.round(np.array([1.2, 2.5, 3.7])))  # [1. 2. 4.]


120
0
4
3.0
[1. 2. 4.]


# Reshaping & Resizing

In [50]:
x = np.arange(1, 10)  # [1 2 3 4 5 6 7 8 9]
y = np.array([[1, 2, 3],
              [4, 5, 6]])

###  1. reshape() → Change shape without changing data

In [51]:
z = x.reshape(3, 3)
print(z)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


### 2. ravel() → Flatten into 1D (returns view if possible)

In [52]:
flat = z.ravel()
print(flat)  # [1 2 3 4 5 6 7 8 9]

[1 2 3 4 5 6 7 8 9]


### 3. flatten() → Flatten into 1D (always returns a copy)  

In [53]:
flat2 = z.flatten()
print(flat2)  # [1 2 3 4 5 6 7 8 9]


[1 2 3 4 5 6 7 8 9]


### 4. resize() → Resize the array in-place  

In [54]:
x.resize((3, 3))
print(x)
# [[1 2 3]
#  [4 5 6]
#  [7 8 9]]


[[1 2 3]
 [4 5 6]
 [7 8 9]]


### 5. Concatenation (np.concatenate)  

In [55]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.concatenate((a, b))
print(c)  # [1 2 3 4 5 6]

# Concatenate 2D arrays vertically (axis=0)
d = np.array([[1, 2], [3, 4]])
e = np.array([[5, 6]])
f = np.concatenate((d, e), axis=0)
print(f)
# [[1 2]
#  [3 4]
#  [5 6]]


[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]


###  6. Stacking (vstack, hstack)

In [56]:
# Vertical stack (rows added)
print(np.vstack((a, b)))
# [[1 2 3]
#  [4 5 6]]

# Horizontal stack (columns added)
print(np.hstack((a, b)))
# [1 2 3 4 5 6]


[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


###  7. Splitting (np.split, hsplit, vsplit)

In [57]:
arr = np.arange(1, 7)  # [1 2 3 4 5 6]
print(np.split(arr, 3))  # [[1 2], [3 4], [5 6]]

# Split 2D array horizontally (columns)
arr2 = np.array([[1,2,3,4], [5,6,7,8]])
print(np.hsplit(arr2, 2))
# [ [[1 2]
#    [5 6]], 
#   [[3 4]
#    [7 8]] ]


[array([1, 2]), array([3, 4]), array([5, 6])]
[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]


# Random Module

###  1. Random Numbers

In [58]:
import numpy as np

# Seed for reproducibility
np.random.seed(42)

# Random integers
rand_int = np.random.randint(1, 10, 5)  # 5 integers between 1 and 9
print(rand_int)  # e.g., [7 4 8 5 7]

# Random floats (0 to 1)
rand_float = np.random.rand(3)  
print(rand_float)  # e.g., [0.37454012 0.95071431 0.73199394]

# Random floats in 2D
rand_matrix = np.random.rand(2, 3)
print(rand_matrix)
# [[0.59865848 0.15601864 0.15599452]
#  [0.05808361 0.86617615 0.60111501]]


[7 4 8 5 7]
[0.44583275 0.09997492 0.45924889]
[[0.33370861 0.14286682 0.65088847]
 [0.05641158 0.72199877 0.93855271]]


###   Normal (Gaussian) Distribution

In [59]:
normal_dist = np.random.randn(5)  # mean=0, std=1
print(normal_dist)  # e.g., [-0.1382643  0.64768854 1.52302986 -0.23415337 -0.23413696]


[ 1.46237812  1.53871497 -2.43910582  0.60344123 -0.25104397]


###  3. Choice / Shuffle

In [60]:
arr = np.array([10, 20, 30, 40, 50])

# Random choice
print(np.random.choice(arr, 3))  # Pick 3 elements randomly

# Shuffle in-place
np.random.shuffle(arr)
print(arr)  # e.g., [30 10 50 40 20]


[30 40 40]
[20 40 50 30 10]


###  4. Special Arrays (zeros, ones, arange, linspace, eye)

In [61]:
print(np.zeros(5))       # [0. 0. 0. 0. 0.]
print(np.ones((2, 3)))   # [[1. 1. 1.]
                          #  [1. 1. 1.]]
print(np.arange(1, 10, 2))  # [1 3 5 7 9]
print(np.linspace(0, 1, 5)) # [0.   0.25 0.5  0.75 1.  ]
print(np.eye(3))            # 3x3 identity matrix
# [[1. 0. 0.]
#  [0. 1. 0.]
#  [0. 0. 1.]]


[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]
[1 3 5 7 9]
[0.   0.25 0.5  0.75 1.  ]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
